// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace septembarski2024.Migrations
{
    [DbContext(typeof(ZadatakContext))]
    [Migration("20241104161416_v4")]
    partial class v4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Models.Racun", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("BrojStana")
                        .HasColumnType("int");

                    b.Property<float>("Komunalije")
                        .HasColumnType("real");

                    b.Property<int>("MesecIzdavanja")
                        .HasColumnType("int");

                    b.Property<bool>("Placen")
                        .HasColumnType("bit");

                    b.Property<float>("Struja")
                        .HasColumnType("real");

                    b.Property<float>("Voda")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("BrojStana");

                    b.ToTable("Racun");
                });

            modelBuilder.Entity("Models.Stan", b =>
                {
                    b.Property<int>("BrojStana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrojStana"), 1L, 1);

                    b.Property<int>("BrojClanova")
                        .HasColumnType("int");

                    b.Property<string>("ImeVlasnika")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Povrsina")
                        .HasMaxLength(100)
                        .HasColumnType("real");

                    b.HasKey("BrojStana");

                    b.ToTable("Stan");
                });

            modelBuilder.Entity("Models.Racun", b =>
                {
                    b.HasOne("Models.Stan", "brojStana")
                        .WithMany("Racuni")
                        .HasForeignKey("BrojStana");

                    b.Navigation("brojStana");
                });

            modelBuilder.Entity("Models.Stan", b =>
                {
                    b.Navigation("Racuni");
                });
#pragma warning restore 612, 618
        }
    }
}
